// <auto-generated />
using System;
using GestionCrud.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionCrud.Migrations
{
    [DbContext(typeof(DBContextColegio))]
    [Migration("20241124233933_123")]
    partial class _123
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GestionCrud.Models.Asignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CalificacionesID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CalificacionesID");

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("GestionCrud.Models.Calificaciones", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Literal")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("GestionCrud.Models.Estudiantes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AsignaturaIDId")
                        .HasColumnType("int");

                    b.Property<int>("CalificacionIDID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AsignaturaIDId");

                    b.HasIndex("CalificacionIDID");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("GestionCrud.Models.Profesor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstudianteIDID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroTelefono")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EstudianteIDID");

                    b.ToTable("Profesor");
                });

            modelBuilder.Entity("GestionCrud.Models.Asignatura", b =>
                {
                    b.HasOne("GestionCrud.Models.Calificaciones", "Calificaciones")
                        .WithMany()
                        .HasForeignKey("CalificacionesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calificaciones");
                });

            modelBuilder.Entity("GestionCrud.Models.Estudiantes", b =>
                {
                    b.HasOne("GestionCrud.Models.Asignatura", "AsignaturaID")
                        .WithMany()
                        .HasForeignKey("AsignaturaIDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionCrud.Models.Calificaciones", "CalificacionID")
                        .WithMany()
                        .HasForeignKey("CalificacionIDID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignaturaID");

                    b.Navigation("CalificacionID");
                });

            modelBuilder.Entity("GestionCrud.Models.Profesor", b =>
                {
                    b.HasOne("GestionCrud.Models.Estudiantes", "EstudianteID")
                        .WithMany()
                        .HasForeignKey("EstudianteIDID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstudianteID");
                });
#pragma warning restore 612, 618
        }
    }
}
